MontyTRC89/Tomb-Editor

README.md
Hi Monty,
I have changed the readme. If you dont like the changes please roll this back.
=> Improved the readability and general grammer.

TombLib/TombLib.Rendering/Rendering/SectorTextures.cs
Previous branch only enabled arrows to be drawn on diagonals, but wasn't doing it properly. This PR fixes this problem.
=> Proper diagonal face arrow indication

TombLib/TombLib/LevelData/Compilers/Rooms.cs
- checking the portal instance' opacity to conditionally match door shades
=> added an additional lookup table from compiled portals to editor portals

TombLib/TombLib/Catalogs/TrCatalog.xml
ID_COMPY = deleted
ID_SMALL_DINOSAUR = ID_COMPSOGNATHUS  (113)
Addition of anim and state names
=> ID_COMPY removal

DarkUI.WPF/Controls/DarkGroupBox.xaml, DarkUI.WPF/Controls/DarkTabControl.xaml, DarkUI.WPF/Generic.xaml, TombEditor.WPF/Forms/FormMain.xaml, TombEditor.WPF/Forms/FormMain.xaml.cs, TombEditor.WPF/Forms/FormOptions.xaml, TombEditor.WPF/Forms/FormOptions.xaml.cs, TombEditor.WPF/ViewModels/OptionsViewModel.cs
Added Style for TabControl
Added Padding for GroupBox
Started ViewModel for FormOptions/Configuration
=> Layout for FormOptions

DarkUI.WPF/Colors/Dark.xaml, TombEditor.WPF/Forms/FormMain.xaml, TombEditor.WPF/Forms/FormOptions.xaml
Added Margin to SpacedGrid
Removed unnecessary ResourceDictionary
=> Added Missing Buttons to FormOptions

TombEditor.WPF/Converters/HtmlToUIColorConverter.cs, TombEditor.WPF/Converters/VectorToUIColorConverter.cs, TombEditor.WPF/Forms/FormOptions.xaml, TombEditor.WPF/Forms/FormOptions.xaml.cs, TombEditor.WPF/ViewModels/OptionsViewModel.cs
@Nickelony 
There is a problem with the color preset selection:
When you change nothing and select a preset, everything works okay.
If you change a single color (via button) and change the preset, the color of the button does not change.
=> Added ViewModel for FormOptions

TombLib/TombLib/Catalogs/TEN Node Catalogs/Dynamic Lights.lua, TombLib/TombLib/Catalogs/TEN Node Catalogs/Particles.lua, TombLib/TombLib/Catalogs/TEN Node Catalogs/_System.lua
Add new Tomb Editor nodes for:
Particle generator
Emit lightning arc
Emit shockwave
Add dynamic light to moveable
Add dynamic light to static
=> Added new nodes from previous PR

TombLib/TombLib/Catalogs/TEN Node Catalogs/Lara.lua
added node 'If Lara is on the vehicle of type...' to check which vehicle Lara is driving
=> added node  'If Lara is on the vehicle of type...'

TombLib/TombLib/LevelData/Instances/CameraInstance.cs, TombLib/TombLib/LevelData/Instances/FlybyCameraInstance.cs, TombLib/TombLib/LevelData/Instances/ItemInstance.cs, TombLib/TombLib/LevelData/Instances/SinkInstance.cs, TombLib/TombLib/LevelData/Instances/SoundSourceInstance.cs, TombLib/TombLib/LevelData/Instances/SpriteInstance.cs, TombLib/TombLib/LevelData/Instances/VolumeInstance.cs
Reduced the string displayed in comboboxes and tooltips information to be simpler and shorter
=> Simplifying node combobox display and information tooltip

TombLib/TombLib/Catalogs/TEN Node Catalogs/Timers.lua
Corrected node to accept only 1 decimal place
=> Timer Node Fix

TombEditor.WPF/Forms/FormTrigger.xaml, TombEditor.WPF/Forms/FormTrigger.xaml.cs
add ***FormTrigger*** in XAML format
=> add FormTrigger

TombEditor.WPF/Views/FormAnimatedTextures.xaml, TombEditor.WPF/Views/FormAnimatedTextures.xaml.cs
Add the form `Animated textures`
=> Add FormAnimatedTextures

Installer/Changes.txt, TombLib/TombLib/Catalogs/TEN Node Catalogs/Particles.lua, TombLib/TombLib/Catalogs/TEN Node Catalogs/Sound.lua
Added TEN node `If sound is playing...` to check if a particular sound is playing. 
Added TEN node `Particle generator (statics)` to generate particles from a static object.
Modified TEN node `Particle generator (moveables)`: added tenths of a second for Lifetime parameter
=> Added TEN nodes and modified TEN node `Particle generator (moveables)`

TombIDE/TombIDE.ScriptingStudio/LuaStudio.cs, TombIDE/TombIDE.Shared/SharedClasses/LevelHandling.cs
- Use of the full namespace in the `Gameflow.lua` and `Settings.lua files`. 
- All general settings are in `Settings.lua`.
- Changed lua code generated when creating a new level
```lua
-- test level
test = TEN.Flow.Level()
test.nameKey = "test"
test.scriptFile = "Scripts\\Levels\\test.lua"
test.ambientTrack = "110"
test.horizon = true
test.levelFile = "Data\\test.ten"
test.loadScreenFile = "Screens\\rome.jpg"
TEN.Flow.AddLevel(test)
--------------------------------------------------
```
=> TEN template editing and code generation

TombEditor/EditorActions.cs, TombLib/TombLib/LevelData/IO/PrjLoader.cs, TombLib/TombLib/LevelData/Room.cs, TombLib/TombLib/LevelData/RoomGeometry.cs
Reverts MontyTRC89/Tomb-Editor#842
=> Revert "Don't rebuild geometry when applying textures"

TombLib/TombLib/Catalogs/TEN Node Catalogs/Revolution.lua
Please test them out. Attached is the test level.
[RevolutionTest.zip](https://github.com/user-attachments/files/16480797/RevolutionTest.zip)
=> Revolution Nodes

TombLib/TombLib/LevelData/Compilers/FloorData.cs
Original plugin floordata code had multiple copypaste lines which are now converted to generic action which is reused multiple times.
=> Decopypaste plugin floordata

TombLib/TombLib.Rendering/Rendering/DirectX11/Dx11RenderingDevice.cs, TombLib/TombLib/Graphics/WadRenderer.cs
- Fixes Texture Upload
- Fixes potential zero sized dimension when resizing a texture
=> Wadrenderer fixes

README.md
haven't used that handle for years, I prefer having my current one here.
=> Update name in README
